TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = sombrero1 sombrero2 sombrero3 sombrero5 sombrero4 sombrero6

clean::
	rm -fr su2 su2adj su3 su3sym sp4 sp4adj
	rm -f *~
	rm -f *.o

include $(MKDIR)/MkRules
