TOPDIR = ..
MKDIR = $(TOPDIR)/Make

SUBDIRS=Error Geometry IO Interface Inverters Memory Random Statistics Update Utils 
LIBDIRS = $(SUBDIRS)

clean::
	rm -fr su2 su2adj su3 su3sym sp4 sp4adj

include $(MKDIR)/MkRules

